
version: '3'

services:

#   MARIA_DB   #

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

#   NGINX   #

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/wordpress
    ports:
      - "443:443"
      #- "8080:8080"
    restart: on-failure

#   WORDPRESS   #

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    expose:
      - "9000"
    restart: on-failure

###   BONUS   ###

#   REDIS   #

  redis:
    container_name: redis
    networks:
      - inception
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    expose:
      - "6379"
    restart: unless-stopped

#   ADMINER   #

  adminer:
    container_name: adminer
    networks:
      - inception
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

#   VSFTPD    #

  vsftpd:
    container_name: vsftpd
    networks:
      - inception
    build:
      context: ./requirements/bonus/vsftpd
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
    restart: unless-stopped

#   NGROK   #

  ngrok:
    container_name: ngrok
    networks:
      - inception
    build:
      context: ./requirements/bonus/ngrok
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "4040:4040"
    restart: unless-stopped


###   END BONUS   ###

#   VOLUMES   #

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: #PATH TO YOUR WORDPRESS#
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: #PATH TO YOUR MARIADB#

networks:
  inception:
    driver: bridge